name: Releases

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: sudo snap install zig --classic --beta
      - uses: actions/cache@v4
        id: zig-cache
        with:
          path: .zig-cache
          key: macOS-zig-cache-${{ github.sha }}
          restore-keys: |
            macOS-zig-cache-
      - run: zig build -Doptimize=ReleaseSmall
      - run: ls ./build
      - run: ./zig-out/bin/tjs test tests
  build:
    runs-on: macos-14
    needs: test
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: brew install zig
      - uses: actions/cache@v4
        id: zig-cache
        with:
          path: .zig-cache
          key: macOS-zig-cache-${{ github.sha }}
          restore-keys: |
            macOS-zig-cache-
      - run: zig build -Dmatrix -Doptimize=ReleaseSmall --summary all
      - uses: actions/upload-artifact@v4
        with:
          name: zig-out
          path: zig-out/*/*
