name: Releases

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: brew install zig
      - uses: actions/cache@v4
        id: zig-cache
        with:
          path: .zig-cache
          key: ${{ runner.os }}-zig-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-zig-cache-
      - run: zig build -Dmatrix -Doptimize=ReleaseSmall --summary all
      - uses: actions/upload-artifact@v4
        with:
          name: zig-out
          path: zig-out/*/*
